{
 "title": "Ethereum RPC nodes performance (Global)",
 "tags": [
  "ethereum",
  "global"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "adhoc", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: inline-flex; align-items: center; margin: 5px; height: 70px;\">\n    <!-- Image Link -->\n    <a href=\"https://chainstack.com/\" target=\"_blank\" style=\"margin-right: 25px; display: inline-block;\">\n        <img src=\"https://chainstack.com/wp-content/themes/chainstack/img/press-kit-logo-white-text.svg\" alt=\"chainstack_logo\" style=\"max-width: 150px; height: auto; display: block;\">\n    </a>\n    \n    <!-- Text Links with Highlight on the First Link -->\n    <a href=\"https://chainstack.grafana.net/public-dashboards/65c0fcb02f994faf845d4ec095771bd0\" target=\"_self\" \n    style=\"text-decoration: none; color: #007bff; font-weight: bold; margin-right: 15px; padding: 5px 10px; border-radius: 5px; \n       background-color: #e0f7fa; border: 1px solid #007bff;\">\n        Ethereum\n    </a>\n    <a href=\"https://chainstack.grafana.net/public-dashboards/11861148d82247128307025fac628b6e\" target=\"_self\" \n    style=\"text-decoration: none; color: #007bff; font-weight: bold; margin-right: 15px; padding: 5px 10px; border-radius: 5px;\">\n        Base\n    </a>\n    <a href=\"https://chainstack.grafana.net/public-dashboards/254601572d9a4b7a90122e46248f82b0\" target=\"_self\" \n       style=\"text-decoration: none; color: #007bff; font-weight: bold; margin-right: 15px; padding: 5px 10px; border-radius: 5px;\">\n        Solana\n    </a>\n    <a href=\"https://chainstack.grafana.net/public-dashboards/deeaf524ea264f42a12718f675511b13\" target=\"_self\" \n       style=\"text-decoration: none; color: #007bff; font-weight: bold; margin-right: 15px; padding: 5px 10px; border-radius: 5px;\">\n        TON\n    </a>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "<div style=\"display: inline-flex; align-items: center; margin: 5px; height: 70px;\">\n    <a href=\"https://chainstack.grafana.net/public-dashboards/65c0fcb02f994faf845d4ec095771bd0\" target=\"_self\" \n       style=\"text-decoration: none; color: #6c757d; font-weight: bold; margin-right: 15px; padding: 5px 10px; border-radius: 5px; \n       background-color: #f8f9fa; border: 1px solid #dee2e6;\">\n        Global\n    </a>\n    <a href=\"https://chainstack.grafana.net/public-dashboards/c41b6d145f5a4f7ebd70cbf0d606b2d7\" target=\"_self\" \n       style=\"text-decoration: none; color: #6c757d; font-weight: bold; margin-right: 15px; padding: 5px 10px; border-radius: 5px;\">\n        US West\n    </a>\n    <a href=\"https://chainstack.grafana.net/public-dashboards/7b313155f59740c086db5527c4409b11\" target=\"_self\" \n       style=\"text-decoration: none; color: #6c757d; font-weight: bold; margin-right: 15px; padding: 5px 10px; border-radius: 5px;\">\n        EU\n    </a>\n    <a href=\"https://chainstack.grafana.net/public-dashboards/f675c8f915f247c8b114ab4fbfbc40bc\" target=\"_self\" \n       style=\"text-decoration: none; color: #6c757d; font-weight: bold; margin-right: 15px; padding: 5px 10px; border-radius: 5px;\">\n        SG\n    </a>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 3 },
   "options": {
    "content": "#### Description\n\nThis dashboard provides real-time and historical performance analytics for RPC nodes across major providers.\n\n* Click region buttons to view metrics from different locations\n* Adjust time range for historical analysis\n* Hover over info icons for detailed metric descriptions"
   }
  },
  {
   "title": "What is the average response time and overall success rate?",
   "type": "text",
   "gridPos": { "h": 1, "w": 14, "x": 10, "y": 3 }
  },
  {
   "title": "By data collection region",
   "type": "barchart",
   "description": "Average response time across all metrics per provider, segmented by request origin region.",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 4 },
   "targets": [
    {
     "expr": "avg by (provider, source_region) (\r\n  avg_over_time(\r\n    response_latency_seconds{blockchain=\"Ethereum\", response_status=\"success\"}[$__range]\r\n  )\r\n)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "stat",
   "description": "Success rate of requests where response has 200 status code and contains no error field in JSON RPC response.",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", response_status=\"success\"}[$__range])) by (provider, source_region)\r\n/\r\nsum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\"}[$__range])) by (provider, source_region)",
     "legendFormat": "{{provider}} - {{source_region}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 10 },
   "options": {
    "content": "#### Data collection\n\nResponse times are measured by our Python service deployed to Vercel serverless functions, sending requests every minute from San Francisco (US), Frankfurt (Germany), and Singapore.\n\nResponse times exceeding 35 seconds are considered failures and excluded from charts."
   }
  },
  {
   "title": "By API method",
   "type": "barchart",
   "description": "Average response time per API method for each provider, aggregated across all regions. Block timestamp delay in eth_subscribe(\"newHeads\")  represents the difference between block timestamp and its reception time.",
   "gridPos": { "h": 9, "w": 8, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_call\", response_status=\"success\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_getBalance\", response_status=\"success\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_getTransactionReceipt\", response_status=\"success\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"debug_traceTransaction\", response_status=\"success\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_blockNumber\", response_status=\"success\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"debug_traceBlockByNumber\", response_status=\"success\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_subscribe\", response_status=\"success\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "What is the average response time in each region?",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "type": "barchart",
   "description": "Average response time per provider-region pair, showing response times between each collection location and provider endpoint.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "avg by (provider, api_method, source_region) (\r\n  avg_over_time(\r\n    response_latency_seconds{blockchain=\"Ethereum\", response_status=\"success\", api_method=~\"(eth_call|eth_getBalance)\"}[$__range]\r\n  )\r\n)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "type": "barchart",
   "description": "Average response time per provider-region pair, showing response times between each collection location and provider endpoint.",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 20 },
   "targets": [
    {
     "expr": "avg by (provider, api_method, source_region) (\r\n  avg_over_time(\r\n    response_latency_seconds{blockchain=\"Ethereum\", response_status=\"success\", api_method=~\"(eth_blockNumber|eth_getTransactionReceipt)\"}[$__range]\r\n  )\r\n)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "type": "barchart",
   "description": "Average response time per provider-region pair, showing response times between each collection location and provider endpoint.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 20 },
   "targets": [
    {
     "expr": "avg by (provider, api_method, source_region) (\r\n  avg_over_time(\r\n    response_latency_seconds{blockchain=\"Ethereum\", response_status=\"success\", api_method=~\"(.*debug.*|eth_subscribe)\"}[$__range]\r\n  )\r\n)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Leaderboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 29 },
     "options": {
      "content": "#### How we rank providers\n\nWe evaluate RPC providers based on their **speed** (response time) and **reliability** (success rate) across three regions.\n\n* The **lower** the score, the **better** the provider\n* Even small success rate drops (99% vs 97%) significantly impact the final score\n* Performance is measured equally across all regions\n\nFor each region:\n```plaintext\nRegionScore = 1 / ((1/ResponseTime) × (SuccessRate³))\n```\nTotal score is the average of three region scores."
     }
    },
    {
     "title": "Total score",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 9, "y": 29 },
     "targets": [
      {
       "expr": "sort(  # Using sort instead of sort_desc since lower is better now\r\n  1 / (\r\n    avg by (provider) (\r\n      (\r\n        1 / avg by (provider, source_region) (\r\n          avg_over_time(\r\n            response_latency_seconds{blockchain=\"Ethereum\", response_status=\"success\"}[$__range]\r\n          )\r\n        )\r\n      )\r\n      *\r\n      (\r\n        (\r\n          sum by (provider, source_region) (rate(response_latency_seconds{blockchain=\"Ethereum\", response_status=\"success\"}[$__range]))\r\n          /\r\n          sum by (provider, source_region) (rate(response_latency_seconds{blockchain=\"Ethereum\"}[$__range]))\r\n        )\r\n        *\r\n        (\r\n          sum by (provider, source_region) (rate(response_latency_seconds{blockchain=\"Ethereum\", response_status=\"success\"}[$__range]))\r\n          /\r\n          sum by (provider, source_region) (rate(response_latency_seconds{blockchain=\"Ethereum\"}[$__range]))\r\n        )\r\n        *\r\n        (\r\n          sum by (provider, source_region) (rate(response_latency_seconds{blockchain=\"Ethereum\", response_status=\"success\"}[$__range]))\r\n          /\r\n          sum by (provider, source_region) (rate(response_latency_seconds{blockchain=\"Ethereum\"}[$__range]))\r\n        )\r\n      )\r\n    )\r\n  )\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Region score",
     "type": "table",
     "gridPos": { "h": 13, "w": 9, "x": 15, "y": 29 },
     "targets": [
      {
       "expr": "sort(\r\n  1 / (\r\n    (\r\n      1 / avg by (provider, source_region) (\r\n        avg_over_time(\r\n          response_latency_seconds{blockchain=\"Ethereum\", response_status=\"success\"}[$__range]\r\n        )\r\n      )\r\n    )\r\n    *\r\n    (\r\n      (\r\n        sum by (provider, source_region) (rate(response_latency_seconds{blockchain=\"Ethereum\", response_status=\"success\"}[$__range]))\r\n        /\r\n        sum by (provider, source_region) (rate(response_latency_seconds{blockchain=\"Ethereum\"}[$__range]))\r\n      )\r\n      *\r\n      (\r\n        sum by (provider, source_region) (rate(response_latency_seconds{blockchain=\"Ethereum\", response_status=\"success\"}[$__range]))\r\n        /\r\n        sum by (provider, source_region) (rate(response_latency_seconds{blockchain=\"Ethereum\"}[$__range]))\r\n      )\r\n      *\r\n      (\r\n        sum by (provider, source_region) (rate(response_latency_seconds{blockchain=\"Ethereum\", response_status=\"success\"}[$__range]))\r\n        /\r\n        sum by (provider, source_region) (rate(response_latency_seconds{blockchain=\"Ethereum\"}[$__range]))\r\n      )\r\n    )\r\n  )\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Historical data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "eth_call",
     "type": "timeseries",
     "description": "Historical response time per provider-region pair, showing trends in eth_call requests.",
     "gridPos": { "h": 12, "w": 19, "x": 0, "y": 289 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_call\", response_status=\"success\"}",
       "legendFormat": "{{provider}} - {{source_region}}"
      }
     ]
    },
    {
     "title": "Success rate",
     "type": "stat",
     "description": "Success rate of requests where response has 200 status code and contains no error field in JSON RPC response.",
     "gridPos": { "h": 12, "w": 5, "x": 19, "y": 289 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_call\", response_status=\"success\"}[$__range])) by (provider, source_region)\r\n/\r\nsum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_call\"}[$__range])) by (provider, source_region)",
       "legendFormat": "{{provider}} - {{source_region}}"
      }
     ]
    },
    {
     "title": "eth_getBalance",
     "type": "timeseries",
     "description": "Historical response time per provider-region pair, showing trends in eth_getBalance requests.",
     "gridPos": { "h": 12, "w": 19, "x": 0, "y": 301 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_getBalance\", response_status=\"success\"}",
       "legendFormat": "{{provider}} - {{source_region}}"
      }
     ]
    },
    {
     "title": "Success rate",
     "type": "stat",
     "description": "Success rate of requests where response has 200 status code and contains no error field in JSON RPC response.",
     "gridPos": { "h": 12, "w": 5, "x": 19, "y": 301 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_getBalance\", response_status=\"success\"}[$__range])) by (provider, source_region)\r\n/\r\nsum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_getBalance\"}[$__range])) by (provider, source_region)",
       "legendFormat": "{{provider}} - {{source_region}}"
      }
     ]
    },
    {
     "title": "eth_getTransactionReceipt",
     "type": "timeseries",
     "description": "Historical response time per provider-region pair, showing trends in eth_getTransactionReceipt requests.",
     "gridPos": { "h": 12, "w": 19, "x": 0, "y": 313 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_getTransactionReceipt\", response_status=\"success\"}",
       "legendFormat": "{{provider}} - {{source_region}}"
      }
     ]
    },
    {
     "title": "Success rate",
     "type": "stat",
     "description": "Success rate of requests where response has 200 status code and contains no error field in JSON RPC response.",
     "gridPos": { "h": 12, "w": 5, "x": 19, "y": 313 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_getTransactionReceipt\", response_status=\"success\"}[$__range])) by (provider, source_region)\r\n/\r\nsum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_getTransactionReceipt\"}[$__range])) by (provider, source_region)",
       "legendFormat": "{{provider}} - {{source_region}}"
      }
     ]
    },
    {
     "title": "debug_traceTransaction",
     "type": "timeseries",
     "description": "Historical response time per provider-region pair, showing trends in debug_traceTransaction requests.",
     "gridPos": { "h": 12, "w": 19, "x": 0, "y": 325 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", api_method=\"debug_traceTransaction\", response_status=\"success\"}",
       "legendFormat": "{{provider}} - {{source_region}}"
      }
     ]
    },
    {
     "title": "Success rate",
     "type": "stat",
     "description": "Success rate of requests where response has 200 status code and contains no error field in JSON RPC response.",
     "gridPos": { "h": 12, "w": 5, "x": 19, "y": 325 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"debug_traceTransaction\", response_status=\"success\"}[$__range])) by (provider, source_region)\r\n/\r\nsum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"debug_traceTransaction\"}[$__range])) by (provider, source_region)",
       "legendFormat": "{{provider}} - {{source_region}}"
      }
     ]
    },
    {
     "title": "eth_blockNumber",
     "type": "timeseries",
     "description": "Historical response time per provider-region pair, showing trends in eth_blockNumber requests.",
     "gridPos": { "h": 12, "w": 19, "x": 0, "y": 337 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_blockNumber\", response_status=\"success\"}",
       "legendFormat": "{{provider}} - {{source_region}}"
      }
     ]
    },
    {
     "title": "Success rate",
     "type": "stat",
     "description": "Success rate of requests where response has 200 status code and contains no error field in JSON RPC response.",
     "gridPos": { "h": 12, "w": 5, "x": 19, "y": 337 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_blockNumber\", response_status=\"success\"}[$__range])) by (provider, source_region)\r\n/\r\nsum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_blockNumber\"}[$__range])) by (provider, source_region)",
       "legendFormat": "{{provider}} - {{source_region}}"
      }
     ]
    },
    {
     "title": "debug_traceBlockByNumber",
     "type": "timeseries",
     "description": "Historical response time per provider-region pair, showing trends in debug_traceBlockByNumber requests.",
     "gridPos": { "h": 12, "w": 19, "x": 0, "y": 349 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", api_method=\"debug_traceBlockByNumber\", response_status=\"success\"}",
       "legendFormat": "{{provider}} - {{source_region}}"
      }
     ]
    },
    {
     "title": "Success rate",
     "type": "stat",
     "description": "Success rate of requests where response has 200 status code and contains no error field in JSON RPC response.",
     "gridPos": { "h": 12, "w": 5, "x": 19, "y": 349 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"debug_traceBlockByNumber\", response_status=\"success\"}[$__range])) by (provider, source_region)\r\n/\r\nsum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"debug_traceBlockByNumber\"}[$__range])) by (provider, source_region)",
       "legendFormat": "{{provider}} - {{source_region}}"
      }
     ]
    },
    {
     "title": "eth_subscribe",
     "type": "timeseries",
     "description": "Historical response time per provider-region pair, showing trends in eth_subscribe(\"newHeads\") - block timestamp delay represents the difference between block timestamp and its reception time.",
     "gridPos": { "h": 12, "w": 19, "x": 0, "y": 361 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_subscribe\", response_status=\"success\"}",
       "legendFormat": "{{provider}} - {{source_region}}"
      }
     ]
    },
    {
     "title": "Success rate",
     "type": "stat",
     "description": "Success rate of events where block delay has been successfully calculated and does not exceed 35 seconds.",
     "gridPos": { "h": 12, "w": 5, "x": 19, "y": 361 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_subscribe\", response_status=\"success\"}[$__range])) by (provider, source_region)\r\n/\r\nsum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_subscribe\"}[$__range])) by (provider, source_region)",
       "legendFormat": "{{provider}} - {{source_region}}"
      }
     ]
    }
   ]
  }
 ]
}