{
 "title": "Ethereum RPC nodes performance (US West)",
 "tags": [
  "ethereum",
  "us-west"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "adhoc", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: inline-flex; align-items: center; margin: 5px; height: 70px;\">\n    <!-- Image Link -->\n    <a href=\"https://chainstack.com/\" target=\"_blank\" style=\"margin-right: 25px; display: inline-block;\">\n        <img src=\"https://chainstack.com/wp-content/themes/chainstack/img/press-kit-logo-white-text.svg\" alt=\"chainstack_logo\" style=\"max-width: 150px; height: auto; display: block;\">\n    </a>\n    \n    <!-- Text Links with Highlight on the First Link -->\n    <a href=\"https://chainstack.grafana.net/public-dashboards/65c0fcb02f994faf845d4ec095771bd0\" target=\"_self\" \n    style=\"text-decoration: none; color: #007bff; font-weight: bold; margin-right: 15px; padding: 5px 10px; border-radius: 5px; \n       background-color: #e0f7fa; border: 1px solid #007bff;\">\n        Ethereum\n    </a>\n    <a href=\"https://chainstack.grafana.net/public-dashboards/11861148d82247128307025fac628b6e\" target=\"_self\" \n    style=\"text-decoration: none; color: #007bff; font-weight: bold; margin-right: 15px; padding: 5px 10px; border-radius: 5px;\">\n        Base\n    </a>\n    <a href=\"https://chainstack.grafana.net/public-dashboards/254601572d9a4b7a90122e46248f82b0\" target=\"_self\" \n       style=\"text-decoration: none; color: #007bff; font-weight: bold; margin-right: 15px; padding: 5px 10px; border-radius: 5px;\">\n        Solana\n    </a>\n    <a href=\"https://chainstack.grafana.net/public-dashboards/deeaf524ea264f42a12718f675511b13\" target=\"_self\" \n       style=\"text-decoration: none; color: #007bff; font-weight: bold; margin-right: 15px; padding: 5px 10px; border-radius: 5px;\">\n        TON\n    </a>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "<div style=\"display: inline-flex; align-items: center; margin: 5px; height: 70px;\">\n    <a href=\"https://chainstack.grafana.net/public-dashboards/65c0fcb02f994faf845d4ec095771bd0\" target=\"_self\" \n       style=\"text-decoration: none; color: #6c757d; font-weight: bold; margin-right: 15px; padding: 5px 10px; border-radius: 5px;\">\n        Global\n    </a>\n    <a href=\"https://chainstack.grafana.net/public-dashboards/c41b6d145f5a4f7ebd70cbf0d606b2d7\" target=\"_self\" \n       style=\"text-decoration: none; color: #6c757d; font-weight: bold; margin-right: 15px; padding: 5px 10px; border-radius: 5px; \n       background-color: #f8f9fa; border: 1px solid #dee2e6;\">\n        US West\n    </a>\n    <a href=\"https://chainstack.grafana.net/public-dashboards/7b313155f59740c086db5527c4409b11\" target=\"_self\" \n       style=\"text-decoration: none; color: #6c757d; font-weight: bold; margin-right: 15px; padding: 5px 10px; border-radius: 5px;\">\n        EU\n    </a>\n    <a href=\"https://chainstack.grafana.net/public-dashboards/f675c8f915f247c8b114ab4fbfbc40bc\" target=\"_self\" \n       style=\"text-decoration: none; color: #6c757d; font-weight: bold; margin-right: 15px; padding: 5px 10px; border-radius: 5px;\">\n        SG\n    </a>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 3 },
   "options": {
    "content": "#### Description\n\nThis dashboard provides real-time and historical performance analytics for RPC nodes across major providers.\n\n* Click region buttons to view metrics from different locations\n* Adjust time range for historical analysis\n* Hover over info icons for detailed metric descriptions"
   }
  },
  {
   "title": "What is the overall success rate of all requests sent from the region?",
   "type": "text",
   "gridPos": { "h": 1, "w": 14, "x": 10, "y": 3 }
  },
  {
   "type": "gauge",
   "description": "Success rate of requests where response has 200 status code and contains no error field in JSON RPC response.",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", response_status=\"success\"}[$__range])) by (provider)\r\n/\r\nsum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\"}[$__range])) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "options": {
    "content": "#### Data collection\n\nResponse times are measured by our Python service deployed to Vercel serverless functions, sending requests every minute from San Francisco (US), Frankfurt (Germany), and Singapore.\n\nResponse times exceeding 35 seconds are considered failures and excluded from charts."
   }
  },
  {
   "title": "What is the average response time?",
   "type": "text",
   "gridPos": { "h": 1, "w": 14, "x": 10, "y": 10 }
  },
  {
   "title": "By API method",
   "type": "barchart",
   "description": "Displays the average response time for each provider. eth_subscribe(\"newHeads\") shows the difference between the block timestamp and its reception time.",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_call\", source_region=\"sfo1\", response_status=\"success\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_getBalance\", source_region=\"sfo1\", response_status=\"success\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_getTransactionReceipt\", source_region=\"sfo1\", response_status=\"success\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"debug_traceTransaction\", source_region=\"sfo1\", response_status=\"success\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_blockNumber\", source_region=\"sfo1\", response_status=\"success\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"debug_traceBlockByNumber\", source_region=\"sfo1\", response_status=\"success\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(response_latency_seconds{blockchain=\"Ethereum\", api_method=\"eth_subscribe\", source_region=\"sfo1\", response_status=\"success\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Historical data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "eth_call",
     "type": "timeseries",
     "description": "Shows how the response time of eth_call has changed over time.",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"eth_call\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "Success rate",
     "type": "stat",
     "description": "Success rate of requests where response has 200 status code and contains no error field in JSON RPC response.",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"eth_call\", response_status=\"success\"}[$__range])) by (provider)\r\n/\r\nsum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"eth_call\"}[$__range])) by (provider)",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "eth_getBalance",
     "type": "timeseries",
     "description": "Shows how the response time of eth_getBalance has changed over time.",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"eth_getBalance\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "Success rate",
     "type": "stat",
     "description": "Success rate of requests where response has 200 status code and contains no error field in JSON RPC response.",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"eth_getBalance\", response_status=\"success\"}[$__range])) by (provider)\r\n/\r\nsum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"eth_getBalance\"}[$__range])) by (provider)",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "eth_getTransactionReceipt",
     "type": "timeseries",
     "description": "Shows how the response time of eth_getTransactionReceipt has changed over time.",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"eth_getTransactionReceipt\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "Success rate",
     "type": "stat",
     "description": "Success rate of requests where response has 200 status code and contains no error field in JSON RPC response.",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"eth_getTransactionReceipt\", response_status=\"success\"}[$__range])) by (provider)\r\n/\r\nsum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"eth_getTransactionReceipt\"}[$__range])) by (provider)",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "debug_traceTransaction",
     "type": "timeseries",
     "description": "Shows how the response time of debug_traceTransaction has changed over time.",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"debug_traceTransaction\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "Success rate",
     "type": "stat",
     "description": "Success rate of requests where response has 200 status code and contains no error field in JSON RPC response.",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"debug_traceTransaction\", response_status=\"success\"}[$__range])) by (provider)\r\n/\r\nsum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"debug_traceTransaction\"}[$__range])) by (provider)",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "eth_blockNumber",
     "type": "timeseries",
     "description": "Shows how the response time of eth_blockNumber has changed over time.",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"eth_blockNumber\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "Success rate",
     "type": "stat",
     "description": "Success rate of requests where response has 200 status code and contains no error field in JSON RPC response.",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"eth_blockNumber\", response_status=\"success\"}[$__range])) by (provider)\r\n/\r\nsum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"eth_blockNumber\"}[$__range])) by (provider)",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "debug_traceBlockByNumber",
     "type": "timeseries",
     "description": "Shows how the response time of debug_traceBlockByNumber has changed over time.",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"debug_traceBlockByNumber\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "Success rate",
     "type": "stat",
     "description": "Success rate of requests where response has 200 status code and contains no error field in JSON RPC response.",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"debug_traceBlockByNumber\", response_status=\"success\"}[$__range])) by (provider)\r\n/\r\nsum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"debug_traceBlockByNumber\"}[$__range])) by (provider)",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "eth_subscribe",
     "type": "timeseries",
     "description": "Shows how the response time of eth_subscribe(\"newHeads\") has changed over time. The difference between the block timestamp and its reception time.",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"eth_subscribe\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "Success rate",
     "type": "stat",
     "description": "Success rate of events where block delay has been successfully calculated and does not exceed 35 seconds.",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"eth_subscribe\", response_status=\"success\"}[$__range])) by (provider)\r\n/\r\nsum(count_over_time(response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", api_method=\"eth_subscribe\"}[$__range])) by (provider)",
       "legendFormat": "{{provider}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Chainstack vs. Quicknode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "eth_call",
     "type": "timeseries",
     "description": "<0 means Chainstack node is faster.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Quicknode-Growth\", api_method=\"eth_call\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      },
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Chainstack\", api_method=\"eth_call\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "eth_getBalance",
     "type": "timeseries",
     "description": "<0 means Chainstack node is faster.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Quicknode-Growth\", api_method=\"eth_getBalance\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      },
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Chainstack\", api_method=\"eth_getBalance\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "eth_getTransactionReceipt",
     "type": "timeseries",
     "description": "<0 means Chainstack node is faster.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Quicknode-Growth\", api_method=\"eth_getTransactionReceipt\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      },
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Chainstack\", api_method=\"eth_getTransactionReceipt\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "debug_traceTransaction",
     "type": "timeseries",
     "description": "<0 means Chainstack node is faster.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Quicknode-Growth\", api_method=\"debug_traceTransaction\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      },
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Chainstack\", api_method=\"debug_traceTransaction\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "eth_blockNumber",
     "type": "timeseries",
     "description": "<0 means Chainstack node is faster.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Quicknode-Growth\", api_method=\"eth_blockNumber\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      },
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Chainstack\", api_method=\"eth_blockNumber\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "debug_traceBlockByNumber",
     "type": "timeseries",
     "description": "<0 means Chainstack node is faster.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Quicknode-Growth\", api_method=\"debug_traceBlockByNumber\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      },
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Chainstack\", api_method=\"debug_traceBlockByNumber\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "eth_subscribe",
     "type": "timeseries",
     "description": "eth_subscribe(\"newHeads\"). <0 means Chainstack node is faster.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Quicknode-Growth\", api_method=\"eth_subscribe\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      },
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Chainstack\", api_method=\"eth_subscribe\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Chainstack vs. Alchemy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "eth_call",
     "type": "timeseries",
     "description": "<0 means Chainstack node is faster.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Alchemy-Growth\", api_method=\"eth_call\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      },
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Chainstack\", api_method=\"eth_call\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "eth_getBalance",
     "type": "timeseries",
     "description": "<0 means Chainstack node is faster.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Alchemy-Growth\", api_method=\"eth_getBalance\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      },
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Chainstack\", api_method=\"eth_getBalance\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "eth_getTransactionReceipt",
     "type": "timeseries",
     "description": "<0 means Chainstack node is faster.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 215 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Alchemy-Growth\", api_method=\"eth_getTransactionReceipt\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      },
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Chainstack\", api_method=\"eth_getTransactionReceipt\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "debug_traceTransaction",
     "type": "timeseries",
     "description": "<0 means Chainstack node is faster.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 215 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Alchemy-Growth\", api_method=\"debug_traceTransaction\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      },
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Chainstack\", api_method=\"debug_traceTransaction\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "eth_blockNumber",
     "type": "timeseries",
     "description": "<0 means Chainstack node is faster.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 220 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Alchemy-Growth\", api_method=\"eth_blockNumber\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      },
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Chainstack\", api_method=\"eth_blockNumber\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "debug_traceBlockByNumber",
     "type": "timeseries",
     "description": "<0 means Chainstack node is faster.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 220 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Alchemy-Growth\", api_method=\"debug_traceBlockByNumber\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      },
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Chainstack\", api_method=\"debug_traceBlockByNumber\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    },
    {
     "title": "eth_subscribe",
     "type": "timeseries",
     "description": "eth_subscribe(\"newHeads\"). <0 means Chainstack node is faster.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 225 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Alchemy-Growth\", api_method=\"eth_subscribe\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      },
      {
       "expr": "response_latency_seconds{blockchain=\"Ethereum\", source_region=\"sfo1\", provider=\"Chainstack\", api_method=\"eth_subscribe\", response_status=\"success\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    }
   ]
  }
 ]
}